# Generated by Django 5.2.1 on 2025-07-19 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('exchange', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('market_cap', models.BigIntegerField()),
                ('last_updated', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'last_updated'], name='market_data_stock_i_787e04_idx'), models.Index(fields=['sector', 'market_cap'], name='market_data_sector_d7a59c_idx'), models.Index(fields=['asset_type'], name='market_data_asset_t_d8d835_idx'), models.Index(fields=['sector', 'asset_type', 'market_cap'], name='market_data_sector_c756da_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockPrice15Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_381b31_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice1D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_dc2505_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_c09ca6_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice1Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_83a338_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_42fec8_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='UnobtainableRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'timeframe', 'start', 'end'], name='market_data_stock_i_d40237_idx')],
                'unique_together': {('stock', 'timeframe', 'start', 'end')},
            },
        ),
    ]
