# Generated by Django 5.2.1 on 2025-07-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice15Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_381b31_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice1D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_dc2505_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_c09ca6_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice1Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_83a338_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='market_data_stock_i_42fec8_idx')],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
    ]
